config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # get "/up/", to: "up#index", as: :up
  # get "/up/databases", to: "up#databases", as: :up_databases

  scope module: :customer do
    get 'login' => 'sessions#new', as: :login
    resources :top, only: [:index]
    resource :session, only: %i[create destroy]
    resources :tasks
    resources :owned_skills, only: %i[create update destroy]
  end

  # Sidekiq has a web dashboard which you can enable below. It's turned off by
  # default because you very likely wouldn't want this to be available to
  # everyone in production.
  #
  # Uncomment the 2 lines below to enable the dashboard WITHOUT authentication,
  # but be careful because even anonymous web visitors will be able to see it!
  # require "sidekiq/web"
  # mount Sidekiq::Web => "/sidekiq"
  #
  # If you add Devise to this project and happen to have an admin? attribute
  # on your user you can uncomment the 4 lines below to only allow access to
  # the dashboard if you're an admin. Feel free to adjust things as needed.
  # require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount Sidekiq::Web => "/sidekiq"
  # end

  # Learn more about this file at: https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/avatar.rb
class Avatar < ApplicationRecord
  # association
  belongs_to :customer
  has_many :owned_skills, dependent: :destroy
  has_many :task_histories, dependent: :destroy

  scope :valid, -> { where(invalidated_at: nil) }
end

app/models/concerns/password_holder.rb
module PasswordHolder
  extend ActiveSupport::Concern

  def password=(raw_password)
    if raw_password.is_a?(String)
      self.hashed_password = BCrypt::Password.create(raw_password)
    elsif raw_password.nil?
      self.hashed_password = nil
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  include PasswordHolder

  # association
  has_one :avatar, dependent: :destroy

  scope :valid, -> { where(invalidated_at: nil) }

  def valid?
    invalidated_at.nil?
  end
end

app/models/experience_column.rb
class ExperienceColumn < ApplicationRecord
  # association
  belongs_to :experience_table

  scope :valid, -> { where(invalidated_at: nil) }
end

app/models/experience_table.rb
class ExperienceTable < ApplicationRecord
  # association
  has_many :experience_columns, dependent: :destroy

  scope :valid, -> { where(invalidated_at: nil) }
end

app/models/owned_skill.rb
class OwnedSkill < ApplicationRecord
  # avatarとskillの中間テーブル。+αでexpやlevelを持っている.
  # association
  belongs_to :avatar
  belongs_to :skill
  scope :valid, -> { where(invalidated_at: nil) }

  def add_exp_point(exp_point)
    update(experience_point: experience_point + exp_point)
  end
end

app/models/rank.rb
class Rank < ApplicationRecord
  scope :valid, -> { where(invalidated_at: nil) }
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :owned_skills, dependent: :destroy
  has_many :tasks, dependent: :destroy
  scope :valid, -> { where(invalidated_at: nil) }
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :task_histories, dependent: :destroy
  belongs_to :skill
  scope :valid, -> { where(invalidated_at: nil) }
end

app/models/task_history.rb
class TaskHistory < ApplicationRecord
  scope :valid, -> { where(invalidated_at: nil) }
  scope :todays, -> { where(completed_at: Time.current.all_day) }
  belongs_to :task
  belongs_to :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customer/base.rb
class Customer::Base < ApplicationController
  private

  def current_customer
    @current_customer ||= Customer.find_by(id: session[:customer_id]) if session[:customer_id]
  end
  helper_method :current_customer
end

app/controllers/customer/owned_skills_controller.rb
class Customer::OwnedSkillsController < Customer::Base
  def update
    @task = Task.find_by(id: params[:id])
    @customer = current_customer
    Customer::TaskHandler.new(@task, current_customer).completed
    # update.turbo_stream.html.erb を返却
  end
end

app/controllers/customer/sessions_controller.rb
class Customer::SessionsController < Customer::Base
  def new
    if current_customer
      redirect_to :top_index
    else
      @form = Customer::LoginForm.new
      render action: 'new'
    end
  end

  # ログイン
  def create
    @form = Customer::LoginForm.new(login_form_params)
    customer = Customer.find_by('LOWER(email) = ?', @form.email.downcase) if @form.email.present?

    if Customer::Authenticator.new(customer).authenticate(@form.password)
      session[:customer_id] = customer.id
      redirect_to :top_index
    else
      render action: 'new'
    end
  end

  def destroy
    session.delete(:customer_id)
    redirect_to :root, status: :see_other
  end

  private

  def login_form_params
    params.require(:customer_login_form).permit(:email, :password)
  end
end

app/controllers/customer/tasks_controller.rb
class Customer::TasksController < Customer::Base
  # top_controllerのindexアクションに移行
  # def index
  #   @tasks = Task.all
  # end

  def new
    @task = Customer::TaskForm.new
  end

  def create
    @task = Customer::TaskForm.new(task_params)
    @task.save
    redirect_to :top_index
  end

  private

  def task_params
    params.require(:customer_task_form).permit(:name, :experience_point, :skill_id, :rank_id)
  end
end

app/controllers/customer/top_controller.rb
class Customer::TopController < Customer::Base
  def index
    @customer = Customer.find_by(id: session[:customer_id])
    # @avatar = @customer.avatar
    @tasks = Task.valid
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  private

  def current_customer
    @current_customer ||= Customer.find_by(id: session[:customer_id]) if session[:customer_id]
  end
  helper_method :current_customer
end

app/controllers/up_controller.rb
class UpController < ApplicationController
  def index
    head :ok
  end

  def databases
    Redis.current.ping
    ActiveRecord::Base.connection.execute('SELECT 1')

    head :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def document_title
    'ToDo RPG App'
    # if @title.present?
    #   "#{@title} - ToDo RPG App"
    # else
    #   'ToDo RPG App'
    # end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/customer/owned_skills/update.turbo_stream.erb
<%# Avatarのレベル・経験値を更新 %>
<%= turbo_stream.update @customer do %>
  <%= render "customer/top/profile", avatar: @customer.avatar %>
<% end %>

<%# 各タスクの実行履歴を更新 %>
<%= turbo_stream.update @task do %>
  <%= render "customer/top/task_list", task: @task %>
<% end %>

app/views/customer/tasks/new.html.erb
<% @title = "新しいタスク" %>

<div id="login-form">
  <h1 class="text-center my-9"><%= @title %></h1>
  <%= form_with model: @task, url: :tasks do |f| %>
    <div className='my-9'>
      <%= f.label :name, "名前", class: "text-gray-700" %>
      <%= f.text_field :name, class: "
          block
          mt-1
          border-gray-300
          rounded-md
          shadow-sm
          focus:border-indigo-300
          focus:ring
          focus:ring-indigo-200
          focus:ring-opacity-50
          border
        "  
      %>
    </div> 
    <div className='my-9'>
      <%= f.label :experience_point, "経験値", class: "text-gray-700" %>
      <%= f.text_field :experience_point, class: "
          block
          mt-1
          border-gray-300
          rounded-md
          shadow-sm
          focus:border-indigo-300
          focus:ring
          focus:ring-indigo-200
          focus:ring-opacity-50
          border
        "  
      %>
    </div> 
    <div className='my-9'>
      <%= f.label :skill_id, "スキル", class: "text-gray-700" %>
      <%= f.select :skill_id, Skill.pluck(:name, :id), { include_blank: true }, class: "
        "  
      %>
    </div> 
    <div className='my-9'>
      <%= f.label :rank_id, "ランク", class: "text-gray-700" %>
      <%= f.select :rank_id, Rank.pluck(:grade, :id), { include_blank: true }, class: "
        "  
      %>
    </div> 

    <div class="text-center" >
      <%= f.submit "新規作成", class: "shadow-lg px-2 py-1  bg-blue-400 text-lg text-white font-semibold rounded  hover:bg-blue-500" %>
    </div>
  <% end %>
  <%= link_to '戻る', :top_index %>
</div>

app/views/customer/top/_profile.html.erb
<div class="flex justify-between w-3/4 px-4 py-3 my-2 mx-auto">
  <% a = AvatarPresenter.new(avatar, self) %>
  <div>
    <%= image_tag "customer/antonio.png", size: "48×48", alt: "アバター画像", class: "mx-auto" %>
    <p><%= avatar.name %></p>
  </div>
  <div class="text-left">
    <%= render "shared/meter", min: 0, max: 50, value: a.total_level, label: "レベル:", content: "#{a.total_level}/50"  %>
    <%= render "shared/meter", min: 0, max: 300, value: a.total_experience_point, label: "経験値:", content: "#{a.total_experience_point}/300"  %>
  </div>
</div>

app/views/customer/top/_task_list.html.erb
<%# NOTE: link_toではなぜかpostメソッドが実行できず、仮でbutton_toにしている %>
<%= button_to owned_skill_path(id: task.id), class: "w-full", method: :patch, remote: true do %>
  <div 
    class="shadow-md bg-white rounded-lg w-3/4 px-4 py-3 my-2 mx-auto cursor-pointer active:shadow"
  >

    <div class="flex justify-between">
      <span></span>
      <span><%= task.name %></span>
      <span><%= task.experience_point %>Pt</span>
    </div>

    <div class="flex justify-between h-3.5">
      <span></span>
      <span></span>
      <% t = TaskPresenter.new(task, self) %>
      <span class="min-w-1/4 text-left">
        Today
        <% if t.today_done_count > 0 %>
          +<%= t.today_done_count %>回
        <% else %>
          not yet ...
        <% end %>
      </span>
    </div>

  </div>
<% end %>

app/views/customer/top/index.html.erb
<% title = "おかえりなさい" %>

<div class="text-center">
  <h1 class="text-3xl m-8"><%= title %></h1>
  <%= turbo_frame_tag @customer do %>
    <%= render "profile", avatar: @customer.avatar %>
  <% end %>
  <div>
    ToDoエリア
    <% @tasks.map do |task| %>
      <%= turbo_frame_tag task do %>
        <%= render "task_list", task: task %>
      <% end %>
    <% end %>
  </div>
  <%= link_to "タスク新規作成", :new_task %>
</div>